# Generated by Django 3.1.4 on 2021-06-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='co2_level',
            new_name='_co2_level',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='co_level',
            new_name='_co_level',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='metano_level',
            new_name='_metano_level',
        ),
    ]
