# Generated by Django 3.1.4 on 2021-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tables', '0002_auto_20210618_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='mac',
            field=models.CharField(max_length=64, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='card_code',
            field=models.CharField(max_length=64, verbose_name='Card Code'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
