# Generated by Django 3.1.4 on 2021-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tables', '0003_auto_20210622_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='#######', max_length=7, verbose_name='Token'),
        ),
    ]
