# Generated by Django 3.1.4 on 2021-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tables', '0004_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=7, verbose_name='Token'),
        ),
    ]
