# Generated by Django 3.1.4 on 2021-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tables', '0005_auto_20210623_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='_lpg_level',
            field=models.FloatField(blank=True, null=True, verbose_name='lpg Level'),
        ),
    ]
