# Generated by Django 3.1.4 on 2021-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tables', '0006_door__lpg_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='_co2_level',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CO2 Level'),
        ),
        migrations.AlterField(
            model_name='door',
            name='_co_level',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='CO Level'),
        ),
        migrations.AlterField(
            model_name='door',
            name='_lpg_level',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='lpg Level'),
        ),
        migrations.AlterField(
            model_name='door',
            name='_metano_level',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Metano Level'),
        ),
    ]
